# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova 12.0.0.0b4.dev203\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-09-16 19:02+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: nova/context.py:109
#, python-format
msgid "Arguments dropped when creating context: %s"
msgstr ""

#: nova/debugger.py:82
msgid ""
"WARNING: Using the remote debug option changes how Nova uses the eventlet"
" library to support async IO. This could result in failures that do not "
"occur under normal operation. Use at your own risk."
msgstr ""

#: nova/service.py:281
msgid "Service killed that has no database entry"
msgstr ""

#: nova/utils.py:242
#, python-format
msgid "Expected to receive %(exp)s bytes, but actually %(act)s"
msgstr ""

#: nova/api/ec2/__init__.py:176
#, python-format
msgid ""
"Access key %(access_key)s has had %(failures)d failed authentications and"
" will be locked out for %(lock_mins)d minutes."
msgstr ""

#: nova/api/ec2/cloud.py:239 nova/objectstore/s3server.py:95
msgid ""
"The in tree EC2 API is deprecated as of Kilo release and may be removed "
"in a future release. The stackforge ec2-api project "
"http://git.openstack.org/cgit/stackforge/ec2-api/ is the target "
"replacement for this functionality."
msgstr ""

#: nova/api/ec2/cloud.py:1333
#, python-format
msgid "multiple fixed_ips exist, using the first: %s"
msgstr ""

#: nova/api/metadata/handler.py:130
msgid ""
"X-Instance-ID present in request headers. The 'service_metadata_proxy' "
"option must be enabled to process this header."
msgstr ""

#: nova/api/metadata/handler.py:294
#, python-format
msgid ""
"X-Instance-ID-Signature: %(signature)s does not match the expected value:"
" %(expected_signature)s for id: %(requestor_id)s. Request From: "
"%(requestor_address)s"
msgstr ""

#: nova/api/metadata/handler.py:323
#, python-format
msgid ""
"Tenant_id %(tenant_id)s does not match tenant_id of instance "
"%(instance_id)s."
msgstr ""

#: nova/api/metadata/vendordata_json.py:47
#, python-format
msgid "%(logprefix)sfile does not exist"
msgstr ""

#: nova/api/metadata/vendordata_json.py:50
#, python-format
msgid "%(logprefix)unexpected IOError when reading"
msgstr ""

#: nova/api/metadata/vendordata_json.py:54
#, python-format
msgid "%(logprefix)sfailed to load json"
msgstr ""

#: nova/api/openstack/__init__.py:286 nova/api/openstack/__init__.py:487
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: nova/api/openstack/__init__.py:341
msgid "In the M release you must run the v2.1 API."
msgstr ""

#: nova/api/openstack/__init__.py:347
msgid ""
"In the M release you must run all of the API. The concept of API "
"extensions will be removed from the codebase to ensure there is a single "
"Compute API."
msgstr ""

#: nova/api/openstack/__init__.py:361
#, python-format
msgid "Extensions in both blacklist and whitelist: %s"
msgstr ""

#: nova/api/openstack/common.py:396
msgid "Rejecting snapshot request, snapshots currently disabled"
msgstr ""

#: nova/api/openstack/extensions.py:214
#, python-format
msgid ""
"The legacy v2 API module already moved "
"into'nova.api.openstack.compute.legacy_v2.contrib'. Use new path instead "
"of old path %s"
msgstr ""

#: nova/api/openstack/extensions.py:238
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: nova/api/openstack/extensions.py:309
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr ""

#: nova/api/openstack/extensions.py:332
#, python-format
msgid "Failed to load extension %(ext_name)s:%(exc)s"
msgstr ""

#: nova/api/openstack/compute/__init__.py:58
msgid ""
"Deprecated: Starting with the Liberty release, the v2 API was already "
"deprecated and the v2.1 API is set as the default. Nova also supports "
"v2.1 API legacy v2 compatible mode for switching to v2.1 API smoothly. "
"For more information on how to configure v2.1 API and legacy v2 "
"compatible mode, please refer Nova api-paste.ini sample file."
msgstr ""

#: nova/api/openstack/compute/__init__.py:173
msgid ""
"Deprecated: The v3 API was deprecated. The v2.1 API replaces it as the "
"Nova API, please refer Nova api-paste.ini sample file for how to "
"configure v2.1 API."
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:200
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:187
#, python-format
msgid "Info cache is %r during associate"
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:232
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:220
#, python-format
msgid "multiple fixed_ips exist, using the first IPv4 fixed_ip: %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:113
#, python-format
msgid "Not loading %s because it is in the blacklist"
msgstr ""

#: nova/api/openstack/compute/servers.py:118
#, python-format
msgid "Not loading %s because it is not in the whitelist"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/extensions.py:45
msgid ""
"The extension configure options are deprecated. In the near future you "
"must run all of the API."
msgstr ""

#: nova/api/openstack/compute/views/servers.py:225
msgid "Instance has had its instance_type removed from the DB"
msgstr ""

#: nova/cells/manager.py:82
msgid ""
"The cells feature of Nova is considered experimental by the OpenStack "
"project because it receives much less testing than the rest of Nova. This"
" may change in the future, but current deployers should be aware that the"
" use of it in production right now may be risky. Also note that cells "
"does not currently support rolling upgrades, it is assumed that cells "
"deployments are upgraded lockstep so n-1 cells compatibility does not "
"work."
msgstr ""

#: nova/cells/manager.py:596
#, python-format
msgid ""
"The same keypair name '%(name)s' exists in the following cells: "
"%(cell_names)s. The keypair value from the first cell is returned."
msgstr ""

#: nova/cells/messaging.py:1189
#, python-format
msgid "No match when trying to update BDM: %(bdm)s"
msgstr ""

#: nova/cells/messaging.py:1682
#, python-format
msgid "No cell_name for %(method)s() from API"
msgstr ""

#: nova/cells/messaging.py:1699
msgid "No cell_name for instance update from API"
msgstr ""

#: nova/cells/weights/mute_child.py:64
#, python-format
msgid ""
"%(cell)s has not been seen since %(last_seen)s and is being treated as "
"mute."
msgstr ""

#: nova/compute/api.py:1604 nova/compute/manager.py:2485
#, python-format
msgid "Failed to delete snapshot from shelved instance (%s)."
msgstr ""

#: nova/compute/api.py:1789
#, python-format
msgid "instance's host %s is down, deleting from database"
msgstr ""

#: nova/compute/api.py:1797 nova/compute/manager.py:2360
msgid "Info cache for instance could not be found. Ignore."
msgstr ""

#: nova/compute/api.py:1839
#, python-format
msgid "Ignoring volume cleanup failure due to %s"
msgstr ""

#: nova/compute/api.py:2652
#, python-format
msgid "%(overs)s quota exceeded for %(pid)s, tried to resize instance."
msgstr ""

#: nova/compute/manager.py:346
#, python-format
msgid "Failed to revert task state for instance. Error: %s"
msgstr ""

#: nova/compute/manager.py:932
#, python-format
msgid ""
"Instance %(uuid)s appears to not be owned by this host, but by %(host)s. "
"Startup processing is being skipped."
msgstr ""

#: nova/compute/manager.py:1067
#, python-format
msgid ""
"Instance in transitional state (%(task_state)s) at start-up and power "
"state is (%(power_state)s), clearing task state"
msgstr ""

#: nova/compute/manager.py:1078
#, python-format
msgid ""
"Instance in transitional state (%(task_state)s) at start-up and power "
"state is (%(power_state)s), clearing task state and unpausing the "
"instance"
msgstr ""

#: nova/compute/manager.py:1181
msgid "Hypervisor driver does not support resume guests"
msgstr ""

#: nova/compute/manager.py:1186
msgid "Failed to resume instance"
msgstr ""

#: nova/compute/manager.py:1196
msgid "Hypervisor driver does not support firewall rules"
msgstr ""

#: nova/compute/manager.py:1240
#, python-format
msgid "Unexpected power state %d"
msgstr ""

#: nova/compute/manager.py:1279
msgid ""
"Instance lifecycle events from the compute driver have been disabled. "
"Note that lifecycle changes to an instance outside of the compute service"
" will not be synchronized automatically since the _sync_power_states "
"periodic task is also disabled."
msgstr ""

#: nova/compute/manager.py:1381
msgid "Hypervisor driver does not support security groups."
msgstr ""

#: nova/compute/manager.py:1398
#, python-format
msgid ""
"Treating negative config value (%(retries)s) for 'block_device_retries' "
"as 0."
msgstr ""

#: nova/compute/manager.py:1414
#, python-format
msgid ""
"Volume id: %(vol_id)s finished being created but its status is "
"%(vol_status)s."
msgstr ""

#: nova/compute/manager.py:1530
msgid "Instance build timed out. Set to error state."
msgstr ""

#: nova/compute/manager.py:1548
#, python-format
msgid ""
"Treating negative config value (%(retries)s) for "
"'network_allocate_retries' as 0."
msgstr ""

#: nova/compute/manager.py:1579
#, python-format
msgid "Instance failed network setup (attempt %(attempt)d of %(attempts)d)"
msgstr ""

#: nova/compute/manager.py:1741
msgid ""
"Failed to create block device for instance due to being over volume "
"resource quota"
msgstr ""

#: nova/compute/manager.py:2025
msgid "No more network or fixed IP to be allocated"
msgstr ""

#: nova/compute/manager.py:2295
#, python-format
msgid "Ignoring EndpointNotFound: %s"
msgstr ""

#: nova/compute/manager.py:2298
#, python-format
msgid "Ignoring Unknown cinder exception: %s"
msgstr ""

#: nova/compute/manager.py:2316 nova/virt/block_device.py:319
#, python-format
msgid "Failed to delete volume: %(volume_id)s due to %(exc)s"
msgstr ""

#: nova/compute/manager.py:2843
#, python-format
msgid ""
"trying to reboot a non-running instance: (state: %(state)s expected: "
"%(running)s)"
msgstr ""

#: nova/compute/manager.py:2879
msgid "Reboot failed but instance is running"
msgstr ""

#: nova/compute/manager.py:2899
msgid "Instance disappeared during reboot"
msgstr ""

#: nova/compute/manager.py:2972
#, python-format
msgid ""
"trying to snapshot a non-running instance: (state: %(state)s expected: "
"%(running)s)"
msgstr ""

#: nova/compute/manager.py:3005
#, python-format
msgid "Error while trying to clean up image %s"
msgstr ""

#: nova/compute/manager.py:3010
msgid "Image not found during snapshot"
msgstr ""

#: nova/compute/manager.py:3105
msgid "set_admin_password is not implemented by this driver or guest instance."
msgstr ""

#: nova/compute/manager.py:3142
#, python-format
msgid ""
"trying to inject a file into a non-running (state: %(current_state)s "
"expected: %(expected_state)s)"
msgstr ""

#: nova/compute/manager.py:3166
msgid ""
"Unable to find a different image to use for rescue VM, using instance's "
"current image"
msgstr ""

#: nova/compute/manager.py:3313
#, python-format
msgid ""
"Unexpected confirmation status '%(status)s' of migration %(id)s, exit "
"confirmation process"
msgstr ""

#: nova/compute/manager.py:4584
msgid "Detaching volume from unknown instance"
msgstr ""

#: nova/compute/manager.py:4595
#, python-format
msgid ""
"Ignoring DiskNotFound exception while detaching volume %(volume_id)s from"
" %(mp)s: %(err)s"
msgstr ""

#: nova/compute/manager.py:4825
#, python-format
msgid ""
"attach interface failed , try to deallocate port %(port_id)s, reason: "
"%(msg)s"
msgstr ""

#: nova/compute/manager.py:4833
#, python-format
msgid "deallocate port %(port_id)s failed"
msgstr ""

#: nova/compute/manager.py:4856 nova/compute/manager.py:6360
#, python-format
msgid "Detach interface failed, port_id=%(port_id)s, reason: %(msg)s"
msgstr ""

#: nova/compute/manager.py:4868
#, python-format
msgid "Failed to deallocate port %(port_id)s for instance. Error: %(error)s"
msgstr ""

#: nova/compute/manager.py:5545
#, python-format
msgid "Setting migration %(migration_id)s to error: %(reason)s"
msgstr ""

#: nova/compute/manager.py:5728
msgid "Bandwidth usage not supported by hypervisor."
msgstr ""

#: nova/compute/manager.py:5857
#, python-format
msgid ""
"While synchronizing instance power states, found %(num_db_instances)s "
"instances in the database and %(num_vm_instances)s instances on the "
"hypervisor."
msgstr ""

#: nova/compute/manager.py:5985
#, python-format
msgid ""
"Instance shutdown by itself. Calling the stop API. Current vm_state: "
"%(vm_state)s, current task_state: %(task_state)s, original DB "
"power_state: %(db_power_state)s, current VM power_state: "
"%(vm_power_state)s"
msgstr ""

#: nova/compute/manager.py:6012
msgid "Instance is suspended unexpectedly. Calling the stop API."
msgstr ""

#: nova/compute/manager.py:6028
msgid "Instance is paused unexpectedly. Ignore."
msgstr ""

#: nova/compute/manager.py:6034
msgid "Instance is unexpectedly not found. Ignore."
msgstr ""

#: nova/compute/manager.py:6040
#, python-format
msgid ""
"Instance is not stopped. Calling the stop API. Current vm_state: "
"%(vm_state)s, current task_state: %(task_state)s, original DB "
"power_state: %(db_power_state)s, current VM power_state: "
"%(vm_power_state)s"
msgstr ""

#: nova/compute/manager.py:6062
msgid "Paused instance shutdown by itself. Calling the stop API."
msgstr ""

#: nova/compute/manager.py:6076
msgid "Instance is not (soft-)deleted."
msgstr ""

#: nova/compute/manager.py:6110
#, python-format
msgid "Periodic reclaim failed to delete instance: %s"
msgstr ""

#: nova/compute/manager.py:6202
#, python-format
msgid ""
"Detected instance with name label '%s' which is marked as DELETED but "
"still present on host."
msgstr ""

#: nova/compute/manager.py:6217
msgid "set_bootable is not implemented for the current driver"
msgstr ""

#: nova/compute/manager.py:6222
msgid "Failed to power off instance"
msgstr ""

#: nova/compute/manager.py:6238
#, python-format
msgid "Periodic cleanup failed to delete instance: %s"
msgstr ""

#: nova/compute/manager.py:6488
#, python-format
msgid "Migration %s is not found."
msgstr ""

#: nova/compute/resource_tracker.py:157
msgid ""
"Host field should not be set on the instance until resources have been "
"claimed."
msgstr ""

#: nova/compute/resource_tracker.py:162
msgid ""
"Node field should not be set on the instance until resources have been "
"claimed."
msgstr ""

#: nova/compute/resource_tracker.py:429
#, python-format
msgid "Cannot get the metrics from %s."
msgstr ""

#: nova/compute/resource_tracker.py:546
#, python-format
msgid "No compute node record for %(host)s:%(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:780
msgid "Instance not resizing, skipping migration."
msgstr ""

#: nova/compute/resource_tracker.py:796
msgid "Flavor could not be found, skipping migration."
msgstr ""

#: nova/compute/resource_tracker.py:885
#, python-format
msgid ""
"Detected running orphan instance: %(uuid)s (consuming %(memory_mb)s MB "
"memory)"
msgstr ""

#: nova/compute/utils.py:212
#, python-format
msgid ""
"Metadata value %(value)s for %(key)s is not of type %(type)s. Using "
"default value %(default)s."
msgstr ""

#: nova/compute/utils.py:336
#, python-format
msgid ""
"No host name specified for the notification of HostAPI.%s and it will be "
"ignored"
msgstr ""

#: nova/compute/utils.py:510
#, python-format
msgid "Flavor %d not found"
msgstr ""

#: nova/compute/monitors/__init__.py:84
#, python-format
msgid ""
"Excluding %(namespace)s monitor %(monitor_name)s. Already loaded "
"%(loaded_monitor)s."
msgstr ""

#: nova/compute/monitors/__init__.py:111
#, python-format
msgid ""
"Excluding %(namespace)s monitor %(monitor_name)s. Not in the list of "
"enabled monitors (CONF.compute_monitors)."
msgstr ""

#: nova/compute/resources/__init__.py:31
#, python-format
msgid "Compute resource plugin %s was not loaded"
msgstr ""

#: nova/conductor/api.py:182
msgid ""
"Timed out waiting for nova-conductor.  Is it running? Or did this service"
" start before nova-conductor?  Reattempting establishment of nova-"
"conductor connection..."
msgstr ""

#: nova/conductor/manager.py:839
msgid "No valid host found for unshelve instance"
msgstr ""

#: nova/conductor/manager.py:882
msgid "No valid host found for rebuild"
msgstr ""

#: nova/conductor/manager.py:890
msgid "Server with unsupported policy cannot be rebuilt"
msgstr ""

#: nova/console/serial.py:98
#, python-format
msgid ""
"serial_console.port_range should be <num>:<num>. Given value "
"%(port_range)s could not be parsed. Taking the default port range "
"%(default)s."
msgstr ""

#: nova/consoleauth/manager.py:86
#, python-format
msgid "Token: %(token)s failed to save into memcached."
msgstr ""

#: nova/consoleauth/manager.py:96
#, python-format
msgid "Instance: %(instance_uuid)s failed to save into memcached"
msgstr ""

#: nova/db/sqlalchemy/api.py:721
#, python-format
msgid "Invalid floating ip id %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:3631
#, python-format
msgid "Change will make usage less than 0 for the following resources: %s"
msgstr ""

#: nova/image/glance.py:220
#, python-format
msgid ""
"Treating negative config value (%(retries)s) for 'glance.num_retries' as "
"0."
msgstr ""

#: nova/keymgr/mock_key_mgr.py:55
msgid "This key manager is not suitable for use in production deployments"
msgstr ""

#: nova/keymgr/single_key_mgr.py:40
msgid ""
"This key manager is insecure and is not recommended for production "
"deployments"
msgstr ""

#: nova/keymgr/single_key_mgr.py:72
#, python-format
msgid "Not deleting key %s"
msgstr ""

#: nova/network/floating_ips.py:195
#, python-format
msgid "Address |%(address)s| is not allocated"
msgstr ""

#: nova/network/floating_ips.py:199
#, python-format
msgid "Address |%(address)s| is not allocated to your project |%(project)s|"
msgstr ""

#: nova/network/floating_ips.py:233
#, python-format
msgid "Quota exceeded for %s, tried to allocate floating IP"
msgstr ""

#: nova/network/floating_ips.py:390
#, python-format
msgid "Failed to disassociated floating address: %s"
msgstr ""

#: nova/network/floating_ips.py:555
#, python-format
msgid ""
"Floating ip address |%(address)s| no longer belongs to instance "
"%(instance_uuid)s. Will not migrate it "
msgstr ""

#: nova/network/floating_ips.py:592
#, python-format
msgid ""
"Floating ip address |%(address)s| no longer belongs to instance "
"%(instance_uuid)s. Will not setup it."
msgstr ""

#: nova/network/floating_ips.py:636
#, python-format
msgid ""
"Database inconsistency: DNS domain |%s| is registered in the Nova db but "
"not visible to either the floating or instance DNS driver. It will be "
"ignored."
msgstr ""

#: nova/network/floating_ips.py:676
#, python-format
msgid "Domain |%(domain)s| already exists, changing zone to |%(av_zone)s|."
msgstr ""

#: nova/network/floating_ips.py:685
#, python-format
msgid "Domain |%(domain)s| already exists, changing project to |%(project)s|."
msgstr ""

#: nova/network/ldapdns.py:108
#, python-format
msgid ""
"Found multiple matches for domain %(domain)s.\n"
"%(entry)s"
msgstr ""

#: nova/network/ldapdns.py:135
#, python-format
msgid "Unable to dequalify.  %(name)s is not in %(domain)s.\n"
msgstr ""

#: nova/network/ldapdns.py:376
msgid "This shouldn't be getting called except during testing."
msgstr ""

#: nova/network/linux_net.py:242
#, python-format
msgid "Attempted to remove chain %s which does not exist"
msgstr ""

#: nova/network/linux_net.py:311
#, python-format
msgid ""
"Tried to remove rule that was not there: %(chain)r %(rule)r %(wrap)r "
"%(top)r"
msgstr ""

#: nova/network/linux_net.py:813
#, python-format
msgid "Removed %(num)d duplicate rules for floating ip %(float)s"
msgstr ""

#: nova/network/linux_net.py:1227
#, python-format
msgid "hostname %s too long, truncating."
msgstr ""

#: nova/network/linux_net.py:1739 nova/network/linux_net.py:1750
#, python-format
msgid "%s failed. Not Retrying."
msgstr ""

#: nova/network/linux_net.py:1743
#, python-format
msgid "%(cmd)s failed. Sleeping %(time)s seconds before retry."
msgstr ""

#: nova/network/manager.py:610
#, python-format
msgid "No VirtualInterface for FixedIP: %s"
msgstr ""

#: nova/network/manager.py:615
#, python-format
msgid "No Network for FixedIP: %s"
msgstr ""

#: nova/network/manager.py:832
#, python-format
msgid "instance-dns-zone not found |%s|."
msgstr ""

#: nova/network/manager.py:839
#, python-format
msgid ""
"instance-dns-zone is |%(domain)s|, which is in availability zone "
"|%(zone)s|. Instance is in zone |%(zone2)s|. No DNS record will be "
"created."
msgstr ""

#: nova/network/manager.py:881
#, python-format
msgid ""
"Quota exceeded for project %(pid)s, tried to allocate fixed IP. %(used)s "
"of %(allowed)s are in use or are already reserved."
msgstr ""

#: nova/network/manager.py:980
msgid "Error cleaning up fixed ip allocation. Manual cleanup may be required."
msgstr ""

#: nova/network/manager.py:1085
#, python-format
msgid "Failed to rollback quota for deallocate fixed ip: %s"
msgstr ""

#: nova/network/manager.py:1098
#, python-format
msgid "IP %s leased that is not associated"
msgstr ""

#: nova/network/manager.py:1104
#, python-format
msgid "IP |%s| leased that isn't allocated"
msgstr ""

#: nova/network/manager.py:1113
#, python-format
msgid "IP %s released that is not associated"
msgstr ""

#: nova/network/manager.py:1117
#, python-format
msgid "IP %s released that was not leased"
msgstr ""

#: nova/network/manager.py:1237
#, python-format
msgid ""
"Subnet(s) too large, defaulting to /%s.  To override, specify "
"network_size flag."
msgstr ""

#: nova/network/minidns.py:122
#, python-format
msgid "Cannot delete entry |%s|"
msgstr ""

#: nova/network/minidns.py:207
#, python-format
msgid "Cannot delete domain |%s|"
msgstr ""

#: nova/network/neutronv2/api.py:347
#, python-format
msgid ""
"Neutron error: %(ip)s is not a valid ip address for network "
"%(network_id)s."
msgstr ""

#: nova/network/neutronv2/api.py:355
#, python-format
msgid "Neutron error: Fixed IP %s is already in use."
msgstr ""

#: nova/network/neutronv2/api.py:360
#, python-format
msgid "Neutron error: Port quota exceeded in tenant: %s"
msgstr ""

#: nova/network/neutronv2/api.py:365
#, python-format
msgid "Neutron error: No more fixed IPs in network: %s"
msgstr ""

#: nova/network/neutronv2/api.py:369
#, python-format
msgid ""
"Neutron error: MAC address %(mac)s is already in use on network "
"%(network)s."
msgstr ""

#: nova/network/neutronv2/api.py:804
#, python-format
msgid "Port %s does not exist"
msgstr ""

#: nova/network/neutronv2/api.py:808
#, python-format
msgid "Failed to delete port %s for instance."
msgstr ""

#: nova/network/neutronv2/api.py:1579
#, python-format
msgid ""
"Network %(id)s not matched with the tenants network! The ports tenant "
"%(tenant_id)s will be used."
msgstr ""

#: nova/network/security_group/neutron_driver.py:467
#, python-format
msgid ""
"Cannot add security group %(name)s to %(instance)s since the port "
"%(port_id)s does not meet security requirements"
msgstr ""

#: nova/objects/instance.py:814
msgid ""
"Trying to apply a migration context that does not seem to be set for this"
" instance"
msgstr ""

#: nova/objects/instance.py:822
msgid ""
"Trying to revert a migration context that does not seem to be set for "
"this instance"
msgstr ""

#: nova/pci/manager.py:131
#, python-format
msgid ""
"Trying to remove device with %(status)s ownership %(instance_uuid)s "
"because of %(pci_exception)s"
msgstr ""

#: nova/pci/manager.py:195
#, python-format
msgid ""
"Assigning a pci device without numa affinity toinstance %(instance)s "
"which has numa topology"
msgstr ""

#: nova/scheduler/host_manager.py:126
#, python-format
msgid "Selected host: %(host)s failed to consume from instance. Error: %(error)s"
msgstr ""

#: nova/scheduler/host_manager.py:209
#, python-format
msgid ""
"Host %(hostname)s has more disk space than database expected "
"(%(physical)sgb > %(database)sgb)"
msgstr ""

#: nova/scheduler/host_manager.py:545
#, python-format
msgid "No compute service record found for host %(host)s"
msgstr ""

#: nova/scheduler/utils.py:95
#, python-format
msgid "Failed to %(service)s_%(method)s: %(ex)s"
msgstr ""

#: nova/scheduler/utils.py:104
#, python-format
msgid "Setting instance to %s state."
msgstr ""

#: nova/scheduler/utils.py:247
#, python-format
msgid "Ignoring the invalid elements of the option %(name)s: %(options)s"
msgstr ""

#: nova/scheduler/utils.py:346
#, python-format
msgid ""
"Retrying %(name)s after a MessagingTimeout, attempt %(attempt)s of "
"%(retries)s."
msgstr ""

#: nova/scheduler/filters/compute_filter.py:47
#, python-format
msgid "%(host_state)s has not been heard from in a while"
msgstr ""

#: nova/scheduler/filters/core_filter.py:40
#: nova/scheduler/filters/exact_core_filter.py:36
msgid "VCPUs not set; assuming CPU collection broken"
msgstr ""

#: nova/scheduler/filters/core_filter.py:97
#, python-format
msgid "Could not decode cpu_allocation_ratio: '%s'"
msgstr ""

#: nova/scheduler/filters/disk_filter.py:83
#, python-format
msgid "Could not decode disk_allocation_ratio: '%s'"
msgstr ""

#: nova/scheduler/filters/io_ops_filter.py:72
#, python-format
msgid "Could not decode max_io_ops_per_host: '%s'"
msgstr ""

#: nova/scheduler/filters/num_instances_filter.py:67
#, python-format
msgid "Could not decode max_instances_per_host: '%s'"
msgstr ""

#: nova/scheduler/filters/ram_filter.py:90
#, python-format
msgid "Could not decode ram_allocation_ratio: '%s'"
msgstr ""

#: nova/servicegroup/api.py:58
#, python-format
msgid ""
"Report interval must be less than service down time. Current config: "
"<service_down_time: %(service_down_time)s, report_interval: "
"%(report_interval)s>. Setting service_down_time to: "
"%(new_service_down_time)s"
msgstr ""

#: nova/servicegroup/drivers/db.py:101
msgid "Lost connection to nova-conductor for reporting service status."
msgstr ""

#: nova/servicegroup/drivers/mc.py:94
msgid "Lost connection to memcache server for reporting service status."
msgstr ""

#: nova/servicegroup/drivers/zk.py:102
msgid ""
"The ZooKeeper service group driver in Nova is not tested by the OpenStack"
" project and thus its quality can not be ensured. This may change in the "
"future, but current deployers should be aware that the use of it in "
"production right now may be risky."
msgstr ""

#: nova/servicegroup/drivers/zk.py:176
#, python-format
msgid ""
"Problem with acquiring the list of children of %(path)r within a given "
"timeout=%(timeout)rs"
msgstr ""

#: nova/virt/configdrive.py:66
msgid ""
"The setting \"always\" will be deprecated in the Liberty version. Please "
"use \"True\" instead"
msgstr ""

#: nova/virt/fake.py:278
#, python-format
msgid "Key '%(key)s' not in instances '%(inst)s'"
msgstr ""

#: nova/virt/storage_users.py:65 nova/virt/storage_users.py:93
#, python-format
msgid "Cannot decode JSON from %(id_path)s"
msgstr ""

#: nova/virt/disk/api.py:261
#, python-format
msgid "Unable to mount image %(image)s with error %(error)s. Cannot resize."
msgstr ""

#: nova/virt/disk/api.py:423
#, python-format
msgid "Ignoring error injecting data into image %(image)s (%(e)s)"
msgstr ""

#: nova/virt/disk/api.py:516
#, python-format
msgid "Ignoring error injecting %(inject)s into image (%(e)s)"
msgstr ""

#: nova/virt/disk/mount/api.py:163
msgid "Device allocation failed after repeated retries."
msgstr ""

#: nova/virt/disk/mount/nbd.py:59
msgid "No free nbd devices"
msgstr ""

#: nova/virt/disk/mount/nbd.py:111
#, python-format
msgid "Detaching from erroneous nbd device returned error: %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:96
msgid ""
"Please consider to execute setup before trying to configure debug log "
"message."
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:200
#, python-format
msgid "Unable to force TCG mode, libguestfs too old? %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:249
#, python-format
msgid "Failed to close augeas %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:257
#, python-format
msgid "Failed to shutdown appliance %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:265
#, python-format
msgid "Failed to close guest handle %s"
msgstr ""

#: nova/virt/hyperv/driver.py:64
msgid ""
"You are running nova-compute on Windows / Hyper-V Server 2008 R2. This "
"version of Windows is deprecated in the current version of OpenStack and "
"the support for it will be removed in the next cycle."
msgstr ""

#: nova/virt/hyperv/eventhandler.py:114
#, python-format
msgid ""
"Instance uuid could not be retrieved for instance %s. Instance state "
"change event will be ignored."
msgstr ""

#: nova/virt/hyperv/snapshotops.py:129
#, python-format
msgid "Failed to remove snapshot for VM %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:507
msgid "Timed out while waiting for soft shutdown."
msgstr ""

#: nova/virt/hyperv/vmutils.py:484
#, python-format
msgid ""
"Disk not found on controller \"%(controller_path)s\" with address "
"\"%(address)s\""
msgstr ""

#: nova/virt/hyperv/volumeops.py:136
msgid "Could not determine iscsi initiator name"
msgstr ""

#: nova/virt/ironic/driver.py:124
#, python-format
msgid "Power state %s not found."
msgstr ""

#: nova/virt/ironic/driver.py:246
#, python-format
msgid "Node %(uuid)s has a malformed \"%(prop)s\". It should be an integer."
msgstr ""

#: nova/virt/ironic/driver.py:257
#, python-format
msgid "cpu_arch not defined for node '%s'"
msgstr ""

#: nova/virt/ironic/driver.py:272
#, python-format
msgid ""
"Node %(uuid)s has a malformed \"%(prop)s\". It should be an integer but "
"its value is \"%(value)s\"."
msgstr ""

#: nova/virt/ironic/driver.py:317
#, python-format
msgid "Ignoring malformed capability '%s'. Format should be 'key:val'."
msgstr ""

#: nova/virt/ironic/driver.py:637
#, python-format
msgid "Warning, memory usage is 0 for %(instance)s on baremetal node %(node)s."
msgstr ""

#: nova/virt/ironic/driver.py:644
#, python-format
msgid "Warning, number of cpus is 0 for %(instance)s on baremetal node %(node)s."
msgstr ""

#: nova/virt/ironic/driver.py:901
#, python-format
msgid "Destroy called on non-existing instance %s."
msgstr ""

#: nova/virt/libvirt/compat.py:35
msgid "Race detected in libvirt.virDomain.info, trying one more time"
msgstr ""

#: nova/virt/libvirt/driver.py:480
#, python-format
msgid "Invalid cachemode %(cache_mode)s specified for disk type %(disk_type)s."
msgstr ""

#: nova/virt/libvirt/driver.py:551
#, python-format
msgid ""
"The libvirt driver is not tested on %(type)s/%(arch)s by the OpenStack "
"project and thus its quality can not be ensured. For more information, "
"see: https://wiki.openstack.org/wiki/HypervisorSupportMatrix"
msgstr ""

#: nova/virt/libvirt/driver.py:573
msgid ""
"Running libvirt-lxc without user namespaces is dangerous. Containers "
"spawned by Nova will be run as the host's root user. It is highly "
"suggested that user namespaces be used in a public or multi-tenant "
"environment."
msgstr ""

#: nova/virt/libvirt/driver.py:601
#, python-format
msgid ""
"Running Nova with a libvirt version less than %(version)s is deprecated. "
"The required minimum version of libvirt will be raised to %(version)s in "
"the 13.0.0 release."
msgstr ""

#: nova/virt/libvirt/driver.py:733
msgid "Cannot destroy instance, operation time out"
msgstr ""

#: nova/virt/libvirt/driver.py:754
#, python-format
msgid ""
"Error from libvirt during destroy. Code=%(errcode)s Error=%(e)s; attempt "
"%(attempt)d of 3"
msgstr ""

#: nova/virt/libvirt/driver.py:854
msgid "Instance may be still running, destroy it again."
msgstr ""

#: nova/virt/libvirt/driver.py:909
#, python-format
msgid "Ignoring Volume Error on vol %(vol_id)s during delete %(exc)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1240 nova/virt/libvirt/driver.py:1249
msgid "During detach_volume, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:1291
msgid "During detach_interface, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:1948
msgid ""
"Relative blockrebase support was not detected. Continuing with old "
"behaviour."
msgstr ""

#: nova/virt/libvirt/driver.py:2058
msgid "Failed to soft reboot instance. Trying hard reboot."
msgstr ""

#: nova/virt/libvirt/driver.py:2557
#, python-format
msgid ""
"my_ip address (%(my_ip)s) was not found on any of the interfaces: "
"%(ifaces)s"
msgstr ""

#: nova/virt/libvirt/driver.py:2770
#, python-format
msgid "Image %s not found on disk storage. Continue without injecting data"
msgstr ""

#: nova/virt/libvirt/driver.py:2969
msgid "File injection into a boot from volume instance is not supported"
msgstr ""

#: nova/virt/libvirt/driver.py:3043
msgid "Instance disappeared while detaching a PCI device from it."
msgstr ""

#: nova/virt/libvirt/driver.py:3153
#, python-format
msgid "Cannot update service status on host \"%s\" since it is not registered."
msgstr ""

#: nova/virt/libvirt/driver.py:3156
#, python-format
msgid ""
"Cannot update service status on host \"%s\" due to an unexpected "
"exception."
msgstr ""

#: nova/virt/libvirt/driver.py:3487
msgid "Too many id maps, only included first five."
msgstr ""

#: nova/virt/libvirt/driver.py:3497
#, python-format
msgid "Invalid value for id mapping %s"
msgstr ""

#: nova/virt/libvirt/driver.py:4253
msgid ""
"Old property name \"hw_watchdog_action\" is now deprecated and will be "
"removed in the next release. Use updated property name "
"\"hw:watchdog_action\" instead"
msgstr ""

#: nova/virt/libvirt/driver.py:4536
#, python-format
msgid "Timeout waiting for vif plugging callback for instance %(uuid)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4562
#, python-format
msgid "couldn't obtain the XML from domain: %(uuid)s, exception: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4602
msgid ""
"Cannot get the number of cpu, because this function is not implemented "
"for this platform. "
msgstr ""

#: nova/virt/libvirt/driver.py:4617
#, python-format
msgid ""
"Couldn't retrieve the online CPUs due to a Libvirt error: %(error)s with "
"error code: %(error_code)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4675
#, python-format
msgid "couldn't obtain the vpu count from domain id: %(uuid)s, exception: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4815
#, python-format
msgid "URI %(uri)s does not support listDevices: %(error)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4834
#, python-format
msgid ""
"You are running with libvirt version %s which is known to have broken "
"NUMA support. Consider patching or updating libvirt on this host if you "
"need NUMA support."
msgstr ""

#: nova/virt/libvirt/driver.py:5533
msgid ""
"Your libvirt version does not support the VIR_DOMAIN_XML_MIGRATABLE flag,"
" and the  graphics (VNC and/or SPICE) listen addresses on the destination"
" node do not match the addresses on the source node. Since the source "
"node has listen addresses set to either the catch-all address (0.0.0.0 or"
" ::) or the local address (127.0.0.1 or ::1), the live migration will "
"succeed, but the VM will continue to listen on the current addresses."
msgstr ""

#: nova/virt/libvirt/driver.py:5632
#, python-format
msgid ""
"An error occurred trying to live migrate. Falling back to legacy live "
"migrate flow. Error: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:5808
#, python-format
msgid "Unable to stat %(disk)s: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:5896
#, python-format
msgid "Live migration stuck for %d sec"
msgstr ""

#: nova/virt/libvirt/driver.py:5902
#, python-format
msgid "Live migration not completed after %d sec"
msgstr ""

#: nova/virt/libvirt/driver.py:5910
#, python-format
msgid "Failed to abort migration %s"
msgstr ""

#: nova/virt/libvirt/driver.py:5930
#, python-format
msgid "Unable to increase max downtime to %(time)dms: %(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:5996
msgid "Migration operation was cancelled"
msgstr ""

#: nova/virt/libvirt/driver.py:6002
#, python-format
msgid "Unexpected migration job type: %d"
msgstr ""

#: nova/virt/libvirt/driver.py:6062
#, python-format
msgid "Error monitoring migration: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:6245
#, python-format
msgid "plug_vifs() failed %(cnt)d. Retry up to %(max_retry)d."
msgstr ""

#: nova/virt/libvirt/driver.py:6519 nova/virt/libvirt/driver.py:6550
#, python-format
msgid ""
"Error from libvirt while getting description of %(instance_name)s: [Error"
" Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:6558
#, python-format
msgid ""
"Periodic task is updating the host stat, it is trying to get disk "
"%(i_name)s, but disk file was removed by concurrent operations such as "
"resize."
msgstr ""

#: nova/virt/libvirt/driver.py:6564
#, python-format
msgid ""
"Periodic task is updating the host stat, it is trying to get disk "
"%(i_name)s, but access is denied. It is most likely due to a VM that "
"exists on the compute node but is not managed by Nova."
msgstr ""

#: nova/virt/libvirt/driver.py:6573
#, python-format
msgid ""
"Periodic task is updating the host stats, it is trying to get disk info "
"for %(i_name)s, but the backing volume block device was removed by "
"concurrent operations such as resize. Error: %(error)s"
msgstr ""

#: nova/virt/libvirt/driver.py:7177
#, python-format
msgid ""
"Ignoring supplied device name: %(device_name)s. Libvirt can't honour "
"user-supplied dev names"
msgstr ""

#: nova/virt/libvirt/driver.py:7200
#, python-format
msgid "Ignoring supplied device name: %(suggested_dev)s"
msgstr ""

#: nova/virt/libvirt/firewall.py:62
msgid ""
"Libvirt module could not be loaded. NWFilterFirewall will not work "
"correctly."
msgstr ""

#: nova/virt/libvirt/host.py:488
#, python-format
msgid "URI %(uri)s does not support events: %(error)s"
msgstr ""

#: nova/virt/libvirt/host.py:504
#, python-format
msgid "URI %(uri)s does not support connection events: %(error)s"
msgstr ""

#: nova/virt/libvirt/host.py:785
#, python-format
msgid "URI %(uri)s does not support full set of host capabilities: %(error)s"
msgstr ""

#: nova/virt/libvirt/host.py:930
#, python-format
msgid "couldn't obtain the memory from domain: %(uuid)s, exception: %(ex)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:333
#, python-format
msgid ""
"Instance %(instance)s is using a backing file %(backing)s which does not "
"appear in the image service"
msgstr ""

#: nova/virt/libvirt/imagecache.py:542
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): warning -- an absent base file is in "
"use! instances: %(instance_list)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:582
#, python-format
msgid "%s swap image was used by instance but no back files existing!"
msgstr ""

#: nova/virt/libvirt/imagecache.py:608
#, python-format
msgid "Unknown base file: %s"
msgstr ""

#: nova/virt/libvirt/instancejobtracker.py:93
#, python-format
msgid ""
"Failed to kill a long running process %(pid)s related to the instance "
"when deleting it."
msgstr ""

#: nova/virt/libvirt/storage/lvm.py:78
#, python-format
msgid ""
"Volume group %(vg)s will not be able to hold sparse volume %(lv)s. "
"Virtual volume size is %(size)db, but free space on volume group is only "
"%(free_space)db."
msgstr ""

#: nova/virt/libvirt/storage/lvm.py:226
#, python-format
msgid "ignoring missing logical volume %(path)s"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:255
#, python-format
msgid "image %(volume)s in pool %(pool)s can not be found, failed to remove"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:286
#, python-format
msgid "rbd remove %(volume)s in pool %(pool)s failed"
msgstr ""

#: nova/virt/libvirt/volume/glusterfs.py:121
#: nova/virt/libvirt/volume/nfs.py:105 nova/virt/libvirt/volume/remotefs.py:64
#, python-format
msgid "%s is already mounted"
msgstr ""

#: nova/virt/libvirt/volume/volume.py:84
#, python-format
msgid "Unknown content in connection_info/qos_specs: %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:205
#, python-format
msgid ""
"Running Nova with a VMware vCenter version less than %(version)s is "
"deprecated. The required minimum version of vCenter will be raised to "
"%(version)s in the 13.0.0 release."
msgstr ""

#: nova/virt/vmwareapi/driver.py:232
msgid "datastore_regex is ignored when PBM is enabled"
msgstr ""

#: nova/virt/vmwareapi/driver.py:485
msgid ""
"Instance does not exists. Proceeding to delete instance properties on "
"datastore"
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:74
#, python-format
msgid "Unable to delete %(file)s. Exception: %(ex)s"
msgstr ""

#: nova/virt/vmwareapi/vif.py:118
#, python-format
msgid ""
"No valid network found in %(opaque)s, from %(bridge)s or "
"%(integration_bridge)s"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1243
#, python-format
msgid "Failed to get cluster references %s"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1290
#, python-format
msgid ""
"vmware_ostype from image is not recognised: '%(ostype)s'. An invalid os "
"type may be one cause of this instance creation failure"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:369
#, python-format
msgid "Get esx cookies failed: %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:473
#, python-format
msgid ""
"Destination %s already exists! Concurrent moves can lead to unexpected "
"results."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1032
#, python-format
msgid ""
"In vmwareapi:vmops:_destroy_instance, got this exception while un-"
"registering the VM: %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1055
msgid ""
"In vmwareapi:vmops:_destroy_instance, exception while deleting the VM "
"contents from the disk"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1059
msgid "Instance does not exist on backend"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1840
#, python-format
msgid "Root disk file creation failed - %s"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:482
#, python-format
msgid "Virtual disk: %s of volume's backing not found."
msgstr ""

#: nova/virt/xenapi/agent.py:194
#, python-format
msgid "Ignoring error while configuring instance with agent: %s"
msgstr ""

#: nova/virt/xenapi/agent.py:270
#, python-format
msgid "Unable to update the agent due to: %(exc)s"
msgstr ""

#: nova/virt/xenapi/agent.py:422
msgid "Invalid 'agent_present' value. Falling back to the default."
msgstr ""

#: nova/virt/xenapi/driver.py:390
#, python-format
msgid "Could not determine key: %s"
msgstr ""

#: nova/virt/xenapi/host.py:293
#, python-format
msgid "Failed to extract instance support from %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:329 nova/virt/xenapi/vm_utils.py:344
msgid "VM already halted, skipping shutdown..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:849
#, python-format
msgid "Multiple base images for image: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:988
#, python-format
msgid "Attempted auto_configure_disk failed because: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1239
#, python-format
msgid ""
"Fast cloning is only supported on default local SR of type ext. SR on "
"this system was found to be of type %s. Ignoring the cow flag."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1314
#, python-format
msgid "Unrecognized cache_images value '%s', defaulting to True"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1390
#, python-format
msgid "Invalid value '%s' for torrent_images"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1413
#, python-format
msgid "Invalid value '%d' for image_compression_level"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1845
#, python-format
msgid "Retry SR scan due to error: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1878
#, python-format
msgid "Flag sr_matching_filter '%s' does not respect formatting convention"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2590
msgid "ipxe_boot_menu_url not set, user will have to enter URL manually..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2596
msgid "ipxe_network_name not set, user will have to enter IP manually..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2607
#, python-format
msgid ""
"Unable to find network matching '%(network_name)s', user will have to "
"enter IP manually..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2631
#, python-format
msgid "ISO creation tool '%s' does not exist."
msgstr ""

#: nova/virt/xenapi/vmops.py:454
msgid "ipxe_boot is True but no ISO image found"
msgstr ""

#: nova/virt/xenapi/vmops.py:1159
#, python-format
msgid "_migrate_disk_resizing_up failed to rollback: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1293
msgid ""
"Reboot failed due to bad volumes, detaching bad volumes and starting "
"halted instance"
msgstr ""

#: nova/virt/xenapi/vmops.py:1371
msgid "Unable to update metadata, VM not found."
msgstr ""

#: nova/virt/xenapi/vmops.py:1523
msgid "VM is not present, skipping destroy..."
msgstr ""

#: nova/virt/xenapi/vmops.py:1652
msgid "VM is not present, skipping soft delete..."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:229
msgid "Cannot purge SR with referenced VDIs"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:246
#, python-format
msgid "Ignoring exception %(exc)s when getting PBDs for %(sr_ref)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:254
#, python-format
msgid "Ignoring exception %(exc)s when unplugging PBD %(pbd)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:278
#, python-format
msgid "Mountpoint cannot be translated: %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:145
#, python-format
msgid "Skipping detach because VBD for %s was not found"
msgstr ""

#: nova/virt/xenapi/client/session.py:249
#, python-format
msgid "%(plugin)s.%(fn)s failed. Retrying call."
msgstr ""

#: nova/virt/xenapi/client/session.py:258
#, python-format
msgid ""
"Lost connection to XenAPI during call to %(plugin)s.%(fn)s.  Retrying "
"call."
msgstr ""

#: nova/virt/xenapi/image/bittorrent.py:73
msgid ""
"Value specified in conf file for xenserver.torrent_base_url does not "
"contain a slash character, therefore it will not be used as part of the "
"torrent URL. Specify a valid base URL as defined by RFC 1808 (see step "
"6)."
msgstr ""

#: nova/volume/cinder.py:121
msgid ""
"Cinder V1 API is deprecated as of the Juno release, and Nova is still "
"configured to use it. Enable the V2 API in Cinder and set "
"cinder.catalog_info in nova.conf to use it."
msgstr ""

#: nova/volume/encryptors/__init__.py:70
#, python-format
msgid "Volume %s should be encrypted but there is no encryption metadata."
msgstr ""

#: nova/volume/encryptors/luks.py:42
#, python-format
msgid "isLuks exited abnormally (status %(exit_code)s): %(stderr)s"
msgstr ""

