# Translations template for nova.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the nova project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova 13.0.0.0b4.dev213\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-03-16 06:22+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: nova/context.py:111
#, python-format
msgid "Arguments dropped when creating context: %s"
msgstr ""

#: nova/debugger.py:82
msgid ""
"WARNING: Using the remote debug option changes how Nova uses the eventlet"
" library to support async IO. This could result in failures that do not "
"occur under normal operation. Use at your own risk."
msgstr ""

#: nova/hooks.py:88
msgid ""
"Hooks are deprecated as of Nova 13.0 and will be removed in a future "
"release"
msgstr ""

#: nova/service.py:312
msgid "Service killed that has no database entry"
msgstr ""

#: nova/utils.py:241
#, python-format
msgid "Expected to receive %(exp)s bytes, but actually %(act)s"
msgstr ""

#: nova/utils.py:779
#, python-format
msgid "Hostname %(hostname)s is longer than 63, truncate it to %(truncated_name)s"
msgstr ""

#: nova/api/ec2/cloud.py:29
msgid ""
"The in tree EC2 API has been removed in Mitaka. Please remove entries "
"from api-paste.ini and use the OpenStack ec2-api project "
"http://git.openstack.org/cgit/openstack/ec2-api/"
msgstr ""

#: nova/api/metadata/handler.py:131
msgid ""
"X-Instance-ID present in request headers. The 'service_metadata_proxy' "
"option must be enabled to process this header."
msgstr ""

#: nova/api/metadata/handler.py:295
#, python-format
msgid ""
"X-Instance-ID-Signature: %(signature)s does not match the expected value:"
" %(expected_signature)s for id: %(requestor_id)s. Request From: "
"%(requestor_address)s"
msgstr ""

#: nova/api/metadata/handler.py:324
#, python-format
msgid ""
"Tenant_id %(tenant_id)s does not match tenant_id of instance "
"%(instance_id)s."
msgstr ""

#: nova/api/metadata/vendordata_json.py:47
#, python-format
msgid "%(logprefix)s file does not exist"
msgstr ""

#: nova/api/metadata/vendordata_json.py:50
#, python-format
msgid "%(logprefix)s unexpected IOError when reading"
msgstr ""

#: nova/api/metadata/vendordata_json.py:54
#, python-format
msgid "%(logprefix)s failed to load json"
msgstr ""

#: nova/api/openstack/__init__.py:317 nova/api/openstack/__init__.py:518
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: nova/api/openstack/__init__.py:372
msgid "In the M release you must run the v2.1 API."
msgstr ""

#: nova/api/openstack/__init__.py:378
msgid ""
"In the M release you must run all of the API. The concept of API "
"extensions will be removed from the codebase to ensure there is a single "
"Compute API."
msgstr ""

#: nova/api/openstack/__init__.py:392
#, python-format
msgid "Extensions in both blacklist and whitelist: %s"
msgstr ""

#: nova/api/openstack/common.py:387
msgid "Rejecting snapshot request, snapshots currently disabled"
msgstr ""

#: nova/api/openstack/extensions.py:214
#, python-format
msgid ""
"The legacy v2 API module already moved "
"into'nova.api.openstack.compute.legacy_v2.contrib'. Use new path instead "
"of old path %s"
msgstr ""

#: nova/api/openstack/extensions.py:238
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: nova/api/openstack/extensions.py:309
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr ""

#: nova/api/openstack/extensions.py:332
#, python-format
msgid "Failed to load extension %(ext_name)s:%(exc)s"
msgstr ""

#: nova/api/openstack/compute/__init__.py:58
msgid ""
"Deprecated: Starting with the Liberty release, the v2 API was already "
"deprecated and the v2.1 API is set as the default. Nova also supports "
"v2.1 API legacy v2 compatible mode for switching to v2.1 API smoothly. "
"For more information on how to configure v2.1 API and legacy v2 "
"compatible mode, please refer Nova api-paste.ini sample file."
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:202
#, python-format
msgid "Info cache is %r during associate with no nw_info cache"
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:234
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:220
#, python-format
msgid "multiple fixed_ips exist, using the first IPv4 fixed_ip: %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:120
#, python-format
msgid ""
"Extension %s is both in whitelist and blacklist, blacklisting takes "
"precedence"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/extensions.py:45
msgid ""
"The extension configure options are deprecated. In the near future you "
"must run all of the API."
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:187
#, python-format
msgid "Info cache is %r during associate"
msgstr ""

#: nova/api/openstack/compute/views/servers.py:224
msgid "Instance has had its instance_type removed from the DB"
msgstr ""

#: nova/cells/manager.py:67
msgid ""
"The cells feature of Nova is considered experimental by the OpenStack "
"project because it receives much less testing than the rest of Nova. This"
" may change in the future, but current deployers should be aware that the"
" use of it in production right now may be risky. Also note that cells "
"does not currently support rolling upgrades, it is assumed that cells "
"deployments are upgraded lockstep so n-1 cells compatibility does not "
"work."
msgstr ""

#: nova/cells/manager.py:581
#, python-format
msgid ""
"The same keypair name '%(name)s' exists in the following cells: "
"%(cell_names)s. The keypair value from the first cell is returned."
msgstr ""

#: nova/cells/messaging.py:1181
#, python-format
msgid "No match when trying to update BDM: %(bdm)s"
msgstr ""

#: nova/cells/messaging.py:1675
#, python-format
msgid "No cell_name for %(method)s() from API"
msgstr ""

#: nova/cells/messaging.py:1692
msgid "No cell_name for instance update from API"
msgstr ""

#: nova/cells/weights/mute_child.py:55
#, python-format
msgid ""
"%(cell)s has not been seen since %(last_seen)s and is being treated as "
"mute."
msgstr ""

#: nova/cmd/compute.py:69 nova/cmd/dhcpbridge.py:138 nova/cmd/network.py:69
msgid ""
"Conductor local mode is deprecated and will be removed in a subsequent "
"release"
msgstr ""

#: nova/compute/api.py:1603 nova/compute/manager.py:2580
#, python-format
msgid "Failed to delete snapshot from shelved instance (%s)."
msgstr ""

#: nova/compute/api.py:1799
#, python-format
msgid "Ignoring volume cleanup failure due to %s"
msgstr ""

#: nova/compute/api.py:1809
#, python-format
msgid "instance's host %s is down, deleting from database"
msgstr ""

#: nova/compute/api.py:2656
#, python-format
msgid "%(overs)s quota exceeded for %(pid)s, tried to resize instance."
msgstr ""

#: nova/compute/claims.py:321
msgid ""
"Can't create a migration_context record without a migration object "
"specified."
msgstr ""

#: nova/compute/manager.py:357
#, python-format
msgid "Failed to revert task state for instance. Error: %s"
msgstr ""

#: nova/compute/manager.py:950
#, python-format
msgid ""
"Instance %(uuid)s appears to not be owned by this host, but by %(host)s. "
"Startup processing is being skipped."
msgstr ""

#: nova/compute/manager.py:1086
#, python-format
msgid ""
"Instance in transitional state (%(task_state)s) at start-up and power "
"state is (%(power_state)s), clearing task state"
msgstr ""

#: nova/compute/manager.py:1097
#, python-format
msgid ""
"Instance in transitional state (%(task_state)s) at start-up and power "
"state is (%(power_state)s), clearing task state and unpausing the "
"instance"
msgstr ""

#: nova/compute/manager.py:1200
msgid "Hypervisor driver does not support resume guests"
msgstr ""

#: nova/compute/manager.py:1205
msgid "Failed to resume instance"
msgstr ""

#: nova/compute/manager.py:1259
#, python-format
msgid "Unexpected power state %d"
msgstr ""

#: nova/compute/manager.py:1298
msgid ""
"Instance lifecycle events from the compute driver have been disabled. "
"Note that lifecycle changes to an instance outside of the compute service"
" will not be synchronized automatically since the _sync_power_states "
"periodic task is also disabled."
msgstr ""

#: nova/compute/manager.py:1405
#, python-format
msgid ""
"Treating negative config value (%(retries)s) for 'block_device_retries' "
"as 0."
msgstr ""

#: nova/compute/manager.py:1421
#, python-format
msgid ""
"Volume id: %(vol_id)s finished being created but its status is "
"%(vol_status)s."
msgstr ""

#: nova/compute/manager.py:1537
msgid "Instance build timed out. Set to error state."
msgstr ""

#: nova/compute/manager.py:1555
#, python-format
msgid ""
"Treating negative config value (%(retries)s) for "
"'network_allocate_retries' as 0."
msgstr ""

#: nova/compute/manager.py:1588
#, python-format
msgid "Instance failed network setup (attempt %(attempt)d of %(attempts)d)"
msgstr ""

#: nova/compute/manager.py:1760
msgid ""
"Failed to create block device for instance due to being over volume "
"resource quota"
msgstr ""

#: nova/compute/manager.py:2086
msgid "No more network or fixed IP to be allocated"
msgstr ""

#: nova/compute/manager.py:2239
#, python-format
msgid "Could not clean up failed build, not rescheduling. Error: %s"
msgstr ""

#: nova/compute/manager.py:2369
#, python-format
msgid "Ignoring EndpointNotFound: %s"
msgstr ""

#: nova/compute/manager.py:2372
#, python-format
msgid "Ignoring Unknown cinder exception: %s"
msgstr ""

#: nova/compute/manager.py:2396 nova/virt/block_device.py:365
#, python-format
msgid "Failed to delete volume: %(volume_id)s due to %(exc)s"
msgstr ""

#: nova/compute/manager.py:2440
msgid "Info cache for instance could not be found. Ignore."
msgstr ""

#: nova/compute/manager.py:3039
#, python-format
msgid ""
"trying to reboot a non-running instance: (state: %(state)s expected: "
"%(running)s)"
msgstr ""

#: nova/compute/manager.py:3075
msgid "Reboot failed but instance is running"
msgstr ""

#: nova/compute/manager.py:3095
msgid "Instance disappeared during reboot"
msgstr ""

#: nova/compute/manager.py:3166
#, python-format
msgid ""
"trying to snapshot a non-running instance: (state: %(state)s expected: "
"%(running)s)"
msgstr ""

#: nova/compute/manager.py:3199
#, python-format
msgid "Error while trying to clean up image %s"
msgstr ""

#: nova/compute/manager.py:3204
msgid "Image not found during snapshot"
msgstr ""

#: nova/compute/manager.py:3299
msgid "set_admin_password is not implemented by this driver or guest instance."
msgstr ""

#: nova/compute/manager.py:3336
#, python-format
msgid ""
"trying to inject a file into a non-running (state: %(current_state)s "
"expected: %(expected_state)s)"
msgstr ""

#: nova/compute/manager.py:3360
msgid ""
"Unable to find a different image to use for rescue VM, using instance's "
"current image"
msgstr ""

#: nova/compute/manager.py:3483
#, python-format
msgid ""
"Unexpected confirmation status '%(status)s' of migration %(id)s, exit "
"confirmation process"
msgstr ""

#: nova/compute/manager.py:4758
msgid "Detaching volume from unknown instance"
msgstr ""

#: nova/compute/manager.py:4769
#, python-format
msgid ""
"Ignoring DiskNotFound exception while detaching volume %(volume_id)s from"
" %(mp)s: %(err)s"
msgstr ""

#: nova/compute/manager.py:4839
#, python-format
msgid ""
"Host mismatch detected, but stashed volume connector not found. Instance "
"host is %(ihost)s, but volume connector host is %(chost)s."
msgstr ""

#: nova/compute/manager.py:5043
#, python-format
msgid ""
"attach interface failed , try to deallocate port %(port_id)s, reason: "
"%(msg)s"
msgstr ""

#: nova/compute/manager.py:5051
#, python-format
msgid "deallocate port %(port_id)s failed"
msgstr ""

#: nova/compute/manager.py:5074 nova/compute/manager.py:6679
#, python-format
msgid "Detach interface failed, port_id=%(port_id)s, reason: %(msg)s"
msgstr ""

#: nova/compute/manager.py:5086
#, python-format
msgid "Failed to deallocate port %(port_id)s for instance. Error: %(error)s"
msgstr ""

#: nova/compute/manager.py:5867
#, python-format
msgid "Setting migration %(migration_id)s to error: %(reason)s"
msgstr ""

#: nova/compute/manager.py:6178
#, python-format
msgid ""
"While synchronizing instance power states, found %(num_db_instances)s "
"instances in the database and %(num_vm_instances)s instances on the "
"hypervisor."
msgstr ""

#: nova/compute/manager.py:6306
#, python-format
msgid ""
"Instance shutdown by itself. Calling the stop API. Current vm_state: "
"%(vm_state)s, current task_state: %(task_state)s, original DB "
"power_state: %(db_power_state)s, current VM power_state: "
"%(vm_power_state)s"
msgstr ""

#: nova/compute/manager.py:6333
msgid "Instance is suspended unexpectedly. Calling the stop API."
msgstr ""

#: nova/compute/manager.py:6349
msgid "Instance is paused unexpectedly. Ignore."
msgstr ""

#: nova/compute/manager.py:6355
msgid "Instance is unexpectedly not found. Ignore."
msgstr ""

#: nova/compute/manager.py:6361
#, python-format
msgid ""
"Instance is not stopped. Calling the stop API. Current vm_state: "
"%(vm_state)s, current task_state: %(task_state)s, original DB "
"power_state: %(db_power_state)s, current VM power_state: "
"%(vm_power_state)s"
msgstr ""

#: nova/compute/manager.py:6383
msgid "Paused instance shutdown by itself. Calling the stop API."
msgstr ""

#: nova/compute/manager.py:6397
msgid "Instance is not (soft-)deleted."
msgstr ""

#: nova/compute/manager.py:6431
#, python-format
msgid "Periodic reclaim failed to delete instance: %s"
msgstr ""

#: nova/compute/manager.py:6521
#, python-format
msgid ""
"Detected instance with name label '%s' which is marked as DELETED but "
"still present on host."
msgstr ""

#: nova/compute/manager.py:6541
msgid "Failed to power off instance"
msgstr ""

#: nova/compute/manager.py:6557
#, python-format
msgid "Periodic cleanup failed to delete instance: %s"
msgstr ""

#: nova/compute/manager.py:6806
#, python-format
msgid "Migration %s is not found."
msgstr ""

#: nova/compute/resource_tracker.py:183
msgid ""
"Host field should not be set on the instance until resources have been "
"claimed."
msgstr ""

#: nova/compute/resource_tracker.py:188
msgid ""
"Node field should not be set on the instance until resources have been "
"claimed."
msgstr ""

#: nova/compute/resource_tracker.py:474
#, python-format
msgid "Cannot get the metrics from %(mon)s; error: %(exc)s"
msgstr ""

#: nova/compute/resource_tracker.py:609
#, python-format
msgid "No compute node record for %(host)s:%(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:846
msgid "Instance not resizing, skipping migration."
msgstr ""

#: nova/compute/resource_tracker.py:864
msgid "Flavor could not be found, skipping migration."
msgstr ""

#: nova/compute/resource_tracker.py:956
#, python-format
msgid ""
"Detected running orphan instance: %(uuid)s (consuming %(memory_mb)s MB "
"memory)"
msgstr ""

#: nova/compute/utils.py:212
#, python-format
msgid ""
"Metadata value %(value)s for %(key)s is not of type %(type)s. Using "
"default value %(default)s."
msgstr ""

#: nova/compute/utils.py:336
#, python-format
msgid ""
"No host name specified for the notification of HostAPI.%s and it will be "
"ignored"
msgstr ""

#: nova/compute/monitors/__init__.py:83
#, python-format
msgid ""
"Excluding %(namespace)s monitor %(monitor_name)s. Already loaded "
"%(loaded_monitor)s."
msgstr ""

#: nova/compute/monitors/__init__.py:109
#, python-format
msgid ""
"Excluding %(namespace)s monitor %(monitor_name)s. Not in the list of "
"enabled monitors (CONF.compute_monitors)."
msgstr ""

#: nova/compute/resources/__init__.py:31
#, python-format
msgid "Compute resource plugin %s was not loaded"
msgstr ""

#: nova/compute/resources/__init__.py:57
msgid ""
"The Extensible Resource Tracker is deprecated and will be removed in the "
"14.0.0 release. If you use this functionality and have custom resources "
"that are managed by the Extensible Resource Tracker, please contact the "
"Nova development team by posting to the openstack-dev mailing list. There"
" is no future planned support for the tracking of custom resources."
msgstr ""

#: nova/conductor/api.py:164
msgid ""
"Timed out waiting for nova-conductor.  Is it running? Or did this service"
" start before nova-conductor?  Reattempting establishment of nova-"
"conductor connection..."
msgstr ""

#: nova/conductor/manager.py:508
msgid "No valid host found for unshelve instance"
msgstr ""

#: nova/conductor/manager.py:565
msgid "No valid host found for rebuild"
msgstr ""

#: nova/conductor/manager.py:573
msgid "Server with unsupported policy cannot be rebuilt"
msgstr ""

#: nova/console/serial.py:76
#, python-format
msgid ""
"serial_console.port_range should be <num>:<num>. Given value "
"%(port_range)s could not be parsed. Taking the default port range "
"%(default)s."
msgstr ""

#: nova/consoleauth/manager.py:103
#, python-format
msgid "Token: %(token)s failed to save into memcached."
msgstr ""

#: nova/consoleauth/manager.py:116
#, python-format
msgid "Instance: %(instance_uuid)s failed to save into memcached"
msgstr ""

#: nova/db/sqlalchemy/api.py:981
#, python-format
msgid "Invalid floating IP ID %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:3894
#, python-format
msgid "Change will make usage less than 0 for the following resources: %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:6342
#, python-format
msgid "IntegrityError detected when archiving table %(tablename)s: %(error)s"
msgstr ""

#: nova/image/glance.py:197
#, python-format
msgid ""
"No protocol specified in for api_server '%s', please update [glance] "
"api_servers with fully qualified url including scheme (http / https)"
msgstr ""

#: nova/image/glance.py:239
#, python-format
msgid ""
"Treating negative config value (%(retries)s) for 'glance.num_retries' as "
"0."
msgstr ""

#: nova/keymgr/mock_key_mgr.py:55
msgid "This key manager is not suitable for use in production deployments"
msgstr ""

#: nova/keymgr/single_key_mgr.py:40
msgid ""
"This key manager is insecure and is not recommended for production "
"deployments"
msgstr ""

#: nova/keymgr/single_key_mgr.py:72
#, python-format
msgid "Not deleting key %s"
msgstr ""

#: nova/network/__init__.py:61
#, python-format
msgid ""
"Config mismatch. The network_api_class specifies %s, however use_neutron "
"is not set to True. Using Neutron networking for now, however please set "
"use_neutron to True in your configuration as network_api_class is "
"deprecated and will be removed."
msgstr ""

#: nova/network/floating_ips.py:195
#, python-format
msgid "Address |%(address)s| is not allocated"
msgstr ""

#: nova/network/floating_ips.py:199
#, python-format
msgid "Address |%(address)s| is not allocated to your project |%(project)s|"
msgstr ""

#: nova/network/floating_ips.py:233
#, python-format
msgid "Quota exceeded for %s, tried to allocate floating IP"
msgstr ""

#: nova/network/floating_ips.py:390
#, python-format
msgid "Failed to disassociated floating address: %s"
msgstr ""

#: nova/network/floating_ips.py:555
#, python-format
msgid ""
"Floating IP address |%(address)s| no longer belongs to instance "
"%(instance_uuid)s. Will not migrate it "
msgstr ""

#: nova/network/floating_ips.py:592
#, python-format
msgid ""
"Floating IP address |%(address)s| no longer belongs to instance "
"%(instance_uuid)s. Will not setup it."
msgstr ""

#: nova/network/floating_ips.py:636
#, python-format
msgid ""
"Database inconsistency: DNS domain |%s| is registered in the Nova db but "
"not visible to either the floating or instance DNS driver. It will be "
"ignored."
msgstr ""

#: nova/network/floating_ips.py:676
#, python-format
msgid "Domain |%(domain)s| already exists, changing zone to |%(av_zone)s|."
msgstr ""

#: nova/network/floating_ips.py:685
#, python-format
msgid "Domain |%(domain)s| already exists, changing project to |%(project)s|."
msgstr ""

#: nova/network/ldapdns.py:108
#, python-format
msgid ""
"Found multiple matches for domain %(domain)s.\n"
"%(entry)s"
msgstr ""

#: nova/network/ldapdns.py:135
#, python-format
msgid "Unable to dequalify.  %(name)s is not in %(domain)s.\n"
msgstr ""

#: nova/network/ldapdns.py:376
msgid "This shouldn't be getting called except during testing."
msgstr ""

#: nova/network/linux_net.py:243
#, python-format
msgid "Attempted to remove chain %s which does not exist"
msgstr ""

#: nova/network/linux_net.py:312
#, python-format
msgid ""
"Tried to remove rule that was not there: %(chain)r %(rule)r %(wrap)r "
"%(top)r"
msgstr ""

#: nova/network/linux_net.py:816
#, python-format
msgid "Removed %(num)d duplicate rules for floating IP %(float)s"
msgstr ""

#: nova/network/linux_net.py:1225
#, python-format
msgid "hostname %s too long, truncating."
msgstr ""

#: nova/network/linux_net.py:1764 nova/network/linux_net.py:1775
#, python-format
msgid "%s failed. Not Retrying."
msgstr ""

#: nova/network/linux_net.py:1768
#, python-format
msgid "%(cmd)s failed. Sleeping %(time)s seconds before retry."
msgstr ""

#: nova/network/manager.py:609
#, python-format
msgid "No VirtualInterface for FixedIP: %s"
msgstr ""

#: nova/network/manager.py:614
#, python-format
msgid "No Network for FixedIP: %s"
msgstr ""

#: nova/network/manager.py:831
#, python-format
msgid "instance-dns-zone not found |%s|."
msgstr ""

#: nova/network/manager.py:838
#, python-format
msgid ""
"instance-dns-zone is |%(domain)s|, which is in availability zone "
"|%(zone)s|. Instance is in zone |%(zone2)s|. No DNS record will be "
"created."
msgstr ""

#: nova/network/manager.py:880
#, python-format
msgid ""
"Quota exceeded for project %(pid)s, tried to allocate fixed IP. %(used)s "
"of %(allowed)s are in use or are already reserved."
msgstr ""

#: nova/network/manager.py:979
msgid "Error cleaning up fixed IP allocation. Manual cleanup may be required."
msgstr ""

#: nova/network/manager.py:1084
#, python-format
msgid "Failed to rollback quota for deallocate fixed IP: %s"
msgstr ""

#: nova/network/manager.py:1097
#, python-format
msgid "IP %s leased that is not associated"
msgstr ""

#: nova/network/manager.py:1103
#, python-format
msgid "IP |%s| leased that isn't allocated"
msgstr ""

#: nova/network/manager.py:1112
#, python-format
msgid "IP %s released that is not associated"
msgstr ""

#: nova/network/manager.py:1116
#, python-format
msgid "IP %s released that was not leased"
msgstr ""

#: nova/network/manager.py:1236
#, python-format
msgid ""
"Subnet(s) too large, defaulting to /%s.  To override, specify "
"network_size flag."
msgstr ""

#: nova/network/minidns.py:118
#, python-format
msgid "Cannot delete entry |%s|"
msgstr ""

#: nova/network/minidns.py:198
#, python-format
msgid "Cannot delete domain |%s|"
msgstr ""

#: nova/network/neutronv2/api.py:163
#, python-format
msgid ""
"%(item)s already exists in list: %(list_name)s containing: %(items)s. "
"ignoring it"
msgstr ""

#: nova/network/neutronv2/api.py:264
#, python-format
msgid ""
"Neutron error: %(ip)s is not a valid IP address for network "
"%(network_id)s."
msgstr ""

#: nova/network/neutronv2/api.py:273
#, python-format
msgid "Neutron error: Fixed IP %s is already in use."
msgstr ""

#: nova/network/neutronv2/api.py:278
#, python-format
msgid "Neutron error: Port quota exceeded in tenant: %s"
msgstr ""

#: nova/network/neutronv2/api.py:283
#, python-format
msgid "Neutron error: No more fixed IPs in network: %s"
msgstr ""

#: nova/network/neutronv2/api.py:287
#, python-format
msgid ""
"Neutron error: MAC address %(mac)s is already in use on network "
"%(network)s."
msgstr ""

#: nova/network/neutronv2/api.py:773
#, python-format
msgid "Neutron error: Instance hostname %(hostname)s is not a valid DNS name"
msgstr ""

#: nova/network/neutronv2/api.py:787
#, python-format
msgid "Port %s does not exist"
msgstr ""

#: nova/network/neutronv2/api.py:792
#, python-format
msgid "Failed to delete port %s for instance."
msgstr ""

#: nova/network/neutronv2/api.py:1595
#, python-format
msgid ""
"Network %(id)s not matched with the tenants network! The ports tenant "
"%(tenant_id)s will be used."
msgstr ""

#: nova/network/security_group/neutron_driver.py:464
#, python-format
msgid ""
"Cannot add security group %(name)s to %(instance)s since the port "
"%(port_id)s does not meet security requirements"
msgstr ""

#: nova/objects/block_device.py:212
#, python-format
msgid "Legacy get_by_volume_id() call found multiple BDMs for volume %(volume)s"
msgstr ""

#: nova/objects/service.py:339
#, python-format
msgid "get_minimum_version called with likely-incorrect binary `%s'"
msgstr ""

#: nova/pci/manager.py:129
#, python-format
msgid ""
"Trying to remove device with %(status)s ownership %(instance_uuid)s "
"because of %(pci_exception)s"
msgstr ""

#: nova/pci/manager.py:192
#, python-format
msgid ""
"Assigning a pci device without numa affinity toinstance %(instance)s "
"which has numa topology"
msgstr ""

#: nova/scheduler/driver.py:57
#, python-format
msgid ""
"DEPRECATED: scheduler_host_manager uses classloader to load %(path)s. "
"This legacy loading style will be removed in the N release."
msgstr ""

#: nova/scheduler/host_manager.py:91
#, python-format
msgid "Selected host: %(host)s failed to consume from instance. Error: %(error)s"
msgstr ""

#: nova/scheduler/host_manager.py:195
#, python-format
msgid ""
"Host %(hostname)s has more disk space than database expected "
"(%(physical)s GB > %(database)s GB)"
msgstr ""

#: nova/scheduler/host_manager.py:562
#, python-format
msgid "No compute service record found for host %(host)s"
msgstr ""

#: nova/scheduler/manager.py:66
#, python-format
msgid ""
"DEPRECATED: scheduler_driver uses classloader to load %(path)s. This "
"legacy loading style will be removed in the N release."
msgstr ""

#: nova/scheduler/utils.py:90
#, python-format
msgid "Failed to %(service)s_%(method)s: %(ex)s"
msgstr ""

#: nova/scheduler/utils.py:99
#, python-format
msgid "Setting instance to %s state."
msgstr ""

#: nova/scheduler/utils.py:248
#, python-format
msgid "Ignoring the invalid elements of the option %(name)s: %(options)s"
msgstr ""

#: nova/scheduler/utils.py:376
#, python-format
msgid ""
"Retrying %(name)s after a MessagingTimeout, attempt %(attempt)s of "
"%(retries)s."
msgstr ""

#: nova/scheduler/filters/compute_filter.py:44
#, python-format
msgid "%(host_state)s has not been heard from in a while"
msgstr ""

#: nova/scheduler/filters/core_filter.py:36
#: nova/scheduler/filters/exact_core_filter.py:32
msgid "VCPUs not set; assuming CPU collection broken"
msgstr ""

#: nova/scheduler/filters/core_filter.py:93
#, python-format
msgid "Could not decode cpu_allocation_ratio: '%s'"
msgstr ""

#: nova/scheduler/filters/disk_filter.py:79
#, python-format
msgid "Could not decode disk_allocation_ratio: '%s'"
msgstr ""

#: nova/scheduler/filters/io_ops_filter.py:64
#, python-format
msgid "Could not decode max_io_ops_per_host: '%s'"
msgstr ""

#: nova/scheduler/filters/num_instances_filter.py:62
#, python-format
msgid "Could not decode max_instances_per_host: '%s'"
msgstr ""

#: nova/scheduler/filters/ram_filter.py:89
#, python-format
msgid "Could not decode ram_allocation_ratio: '%s'"
msgstr ""

#: nova/scheduler/filters/trusted_filter.py:234
msgid ""
"The TrustedFilter is considered experimental by the OpenStack project "
"because it receives much less testing than the rest of Nova. This may "
"change in the future, but current deployers should be aware that the use "
"of it in production right now may be risky."
msgstr ""

#: nova/scheduler/weights/affinity.py:63
msgid ""
"For the soft_affinity_weight_multiplier only a positive value is "
"meaningful as a negative value would mean that the affinity weigher would"
" prefer non-collocating placement."
msgstr ""

#: nova/scheduler/weights/affinity.py:79
msgid ""
"For the soft_anti_affinity_weight_multiplier only a positive value is "
"meaningful as a negative value would mean that the anti-affinity weigher "
"would prefer collocating placement."
msgstr ""

#: nova/servicegroup/api.py:58
#, python-format
msgid ""
"Report interval must be less than service down time. Current config: "
"<service_down_time: %(service_down_time)s, report_interval: "
"%(report_interval)s>. Setting service_down_time to: "
"%(new_service_down_time)s"
msgstr ""

#: nova/servicegroup/drivers/db.py:102
msgid "Lost connection to nova-conductor for reporting service status."
msgstr ""

#: nova/servicegroup/drivers/mc.py:92
msgid "Lost connection to memcache server for reporting service status."
msgstr ""

#: nova/virt/block_device.py:314
#, python-format
msgid "Driver failed to detach volume %(volume_id)s at %(mount_point)s."
msgstr ""

#: nova/virt/fake.py:275
#, python-format
msgid "Key '%(key)s' not in instances '%(inst)s'"
msgstr ""

#: nova/virt/osinfo.py:96
#, python-format
msgid "Cannot find OS information - Reason: (%s)"
msgstr ""

#: nova/virt/storage_users.py:65 nova/virt/storage_users.py:93
#, python-format
msgid "Cannot decode JSON from %(id_path)s"
msgstr ""

#: nova/virt/disk/api.py:235
#, python-format
msgid "Unable to mount image %(image)s with error %(error)s. Cannot resize."
msgstr ""

#: nova/virt/disk/api.py:399
#, python-format
msgid "Ignoring error injecting data into image %(image)s (%(e)s)"
msgstr ""

#: nova/virt/disk/api.py:495
#, python-format
msgid "Ignoring error injecting %(inject)s into image (%(e)s)"
msgstr ""

#: nova/virt/disk/mount/api.py:170
msgid "Device allocation failed after repeated retries."
msgstr ""

#: nova/virt/disk/mount/nbd.py:51
msgid "No free nbd devices"
msgstr ""

#: nova/virt/disk/mount/nbd.py:103
#, python-format
msgid "Detaching from erroneous nbd device returned error: %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:96
msgid ""
"Please consider to execute setup before trying to configure debug log "
"message."
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:200
#, python-format
msgid "Unable to force TCG mode, libguestfs too old? %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:249
#, python-format
msgid "Failed to close augeas %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:257
#, python-format
msgid "Failed to shutdown appliance %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:265
#, python-format
msgid "Failed to close guest handle %s"
msgstr ""

#: nova/virt/hyperv/eventhandler.py:115
#, python-format
msgid ""
"Instance uuid could not be retrieved for instance %s. Instance state "
"change event will be ignored."
msgstr ""

#: nova/virt/hyperv/vmops.py:514
msgid "Timed out while waiting for soft shutdown."
msgstr ""

#: nova/virt/hyperv/volumeops.py:141
msgid "Could not determine iscsi initiator name"
msgstr ""

#: nova/virt/ironic/driver.py:86
#, python-format
msgid "Power state %s not found."
msgstr ""

#: nova/virt/ironic/driver.py:213
#, python-format
msgid "Node %(uuid)s has a malformed \"%(prop)s\". It should be an integer."
msgstr ""

#: nova/virt/ironic/driver.py:224
#, python-format
msgid "cpu_arch not defined for node '%s'"
msgstr ""

#: nova/virt/ironic/driver.py:249
#, python-format
msgid ""
"Node %(uuid)s has a malformed \"%(prop)s\". It should be an integer but "
"its value is \"%(value)s\"."
msgstr ""

#: nova/virt/ironic/driver.py:294
#, python-format
msgid "Ignoring malformed capability '%s'. Format should be 'key:val'."
msgstr ""

#: nova/virt/ironic/driver.py:594
#, python-format
msgid "Warning, memory usage is 0 for %(instance)s on baremetal node %(node)s."
msgstr ""

#: nova/virt/ironic/driver.py:601
#, python-format
msgid "Warning, number of cpus is 0 for %(instance)s on baremetal node %(node)s."
msgstr ""

#: nova/virt/ironic/driver.py:855
#, python-format
msgid "Destroy called on non-existing instance %s."
msgstr ""

#: nova/virt/libvirt/compat.py:35
msgid "Race detected in libvirt.virDomain.info, trying one more time"
msgstr ""

#: nova/virt/libvirt/driver.py:560
#, python-format
msgid "Invalid cachemode %(cache_mode)s specified for disk type %(disk_type)s."
msgstr ""

#: nova/virt/libvirt/driver.py:626
#, python-format
msgid ""
"The libvirt driver is not tested on %(type)s/%(arch)s by the OpenStack "
"project and thus its quality can not be ensured. For more information, "
"see: https://wiki.openstack.org/wiki/HypervisorSupportMatrix"
msgstr ""

#: nova/virt/libvirt/driver.py:650
msgid ""
"Running libvirt-lxc without user namespaces is dangerous. Containers "
"spawned by Nova will be run as the host's root user. It is highly "
"suggested that user namespaces be used in a public or multi-tenant "
"environment."
msgstr ""

#: nova/virt/libvirt/driver.py:677
#, python-format
msgid ""
"Running Nova with a libvirt version less than %(version)s is deprecated. "
"The required minimum version of libvirt will be raised to %(version)s in "
"the next release."
msgstr ""

#: nova/virt/libvirt/driver.py:703
#, python-format
msgid ""
"Removing the VIR_MIGRATE_PEER2PEER flag from %(config_name)s because "
"peer-to-peer migrations are not supported by the \"xen\" virt type"
msgstr ""

#: nova/virt/libvirt/driver.py:711
#, python-format
msgid ""
"Adding the VIR_MIGRATE_PEER2PEER flag to %(config_name)s because direct "
"migrations are not supported by the %(virt_type)s virt type"
msgstr ""

#: nova/virt/libvirt/driver.py:720
#, python-format
msgid ""
"Adding the VIR_MIGRATE_UNDEFINE_SOURCE flag to %(config_name)s because, "
"without it, migrated VMs will remain defined on the source host"
msgstr ""

#: nova/virt/libvirt/driver.py:727
#, python-format
msgid ""
"Removing the VIR_MIGRATE_PERSIST_DEST flag from %(config_name)s as Nova "
"ensures the VM is persisted on the destination host"
msgstr ""

#: nova/virt/libvirt/driver.py:738
msgid ""
"Removing the VIR_MIGRATE_NON_SHARED_INC flag from the live_migration_flag"
" config option because it will cause all live-migrations to be block-"
"migrations instead."
msgstr ""

#: nova/virt/libvirt/driver.py:745
msgid ""
"Adding the VIR_MIGRATE_NON_SHARED_INC flag to the block_migration_flag "
"config option, otherwise all block-migrations will be live-migrations "
"instead."
msgstr ""

#: nova/virt/libvirt/driver.py:759
#, python-format
msgid ""
"The %(config_name)s config option does not contain the "
"VIR_MIGRATE_TUNNELLED flag but the live_migration_tunnelled is set to "
"True which causes VIR_MIGRATE_TUNNELLED to be set"
msgstr ""

#: nova/virt/libvirt/driver.py:768
#, python-format
msgid ""
"The %(config_name)s config option contains the VIR_MIGRATE_TUNNELLED flag"
" but the live_migration_tunnelled is set to False which causes "
"VIR_MIGRATE_TUNNELLED to be unset"
msgstr ""

#: nova/virt/libvirt/driver.py:785
#, python-format
msgid "Ignoring unknown libvirt live migration flag '%(flag)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:942
msgid "Cannot destroy instance, operation time out"
msgstr ""

#: nova/virt/libvirt/driver.py:963
#, python-format
msgid ""
"Error from libvirt during destroy. Code=%(errcode)s Error=%(e)s; attempt "
"%(attempt)d of 3"
msgstr ""

#: nova/virt/libvirt/driver.py:1063
msgid "Instance may be still running, destroy it again."
msgstr ""

#: nova/virt/libvirt/driver.py:1118
#, python-format
msgid "Ignoring Volume Error on vol %(vol_id)s during delete %(exc)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1474 nova/virt/libvirt/driver.py:1485
msgid "During detach_volume, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:1526
msgid "During detach_interface, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:1549
#, python-format
msgid ""
"Detaching interface %(mac)s failed  because the device is no longer found"
" on the guest."
msgstr ""

#: nova/virt/libvirt/driver.py:1695
#, python-format
msgid "Performing standard snapshot because direct snapshot failed: %(error)s"
msgstr ""

#: nova/virt/libvirt/driver.py:2282
msgid ""
"Relative blockrebase support was not detected. Continuing with old "
"behaviour."
msgstr ""

#: nova/virt/libvirt/driver.py:2401
msgid "Failed to soft reboot instance. Trying hard reboot."
msgstr ""

#: nova/virt/libvirt/driver.py:2873
#, python-format
msgid ""
"my_ip address (%(my_ip)s) was not found on any of the interfaces: "
"%(ifaces)s"
msgstr ""

#: nova/virt/libvirt/driver.py:3080
#, python-format
msgid "Image %s not found on disk storage. Continue without injecting data"
msgstr ""

#: nova/virt/libvirt/driver.py:3284
msgid "File injection into a boot from volume instance is not supported"
msgstr ""

#: nova/virt/libvirt/driver.py:3358
msgid "Instance disappeared while detaching a PCI device from it."
msgstr ""

#: nova/virt/libvirt/driver.py:3477
#, python-format
msgid "Cannot update service status on host \"%s\" since it is not registered."
msgstr ""

#: nova/virt/libvirt/driver.py:3480
#, python-format
msgid ""
"Cannot update service status on host \"%s\" due to an unexpected "
"exception."
msgstr ""

#: nova/virt/libvirt/driver.py:3807
msgid "Too many id maps, only included first five."
msgstr ""

#: nova/virt/libvirt/driver.py:3817
#, python-format
msgid "Invalid value for id mapping %s"
msgstr ""

#: nova/virt/libvirt/driver.py:4375
msgid ""
"uefi support is without some kind of functional testing and therefore "
"considered experimental."
msgstr ""

#: nova/virt/libvirt/driver.py:4636
msgid ""
"Old property name \"hw_watchdog_action\" is now deprecated and will be "
"removed in the next release. Use updated property name "
"\"hw:watchdog_action\" instead"
msgstr ""

#: nova/virt/libvirt/driver.py:4920
#, python-format
msgid "Timeout waiting for vif plugging callback for instance %(uuid)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4944
msgid ""
"Cannot get the number of cpu, because this function is not implemented "
"for this platform. "
msgstr ""

#: nova/virt/libvirt/driver.py:4959
#, python-format
msgid ""
"Couldn't retrieve the online CPUs due to a Libvirt error: %(error)s with "
"error code: %(error_code)s"
msgstr ""

#: nova/virt/libvirt/driver.py:5015
#, python-format
msgid "couldn't obtain the vcpu count from domain id: %(uuid)s, exception: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:5165
#, python-format
msgid "URI %(uri)s does not support listDevices: %(error)s"
msgstr ""

#: nova/virt/libvirt/driver.py:5184
#, python-format
msgid ""
"You are running with libvirt version %s which is known to have broken "
"NUMA support. Consider patching or updating libvirt on this host if you "
"need NUMA support."
msgstr ""

#: nova/virt/libvirt/driver.py:5923
msgid ""
"Your libvirt version does not support the VIR_DOMAIN_XML_MIGRATABLE flag,"
" and the graphics (VNC and/or SPICE) listen addresses on the destination "
"node do not match the addresses on the source node. Since the source node"
" has listen addresses set to either the catch-all address (0.0.0.0 or ::)"
" or the local address (127.0.0.1 or ::1), the live migration will "
"succeed, but the VM will continue to listen on the current addresses."
msgstr ""

#: nova/virt/libvirt/driver.py:6042
#, python-format
msgid ""
"An error occurred trying to live migrate. Falling back to legacy live "
"migrate flow. Error: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:6225
#, python-format
msgid "Unable to stat %(disk)s: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:6314
#, python-format
msgid "Live migration stuck for %d sec"
msgstr ""

#: nova/virt/libvirt/driver.py:6320
#, python-format
msgid "Live migration not completed after %d sec"
msgstr ""

#: nova/virt/libvirt/driver.py:6328
#, python-format
msgid "Failed to abort migration %s"
msgstr ""

#: nova/virt/libvirt/driver.py:6348
#, python-format
msgid "Unable to increase max downtime to %(time)dms: %(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:6424
msgid "Migration operation was cancelled"
msgstr ""

#: nova/virt/libvirt/driver.py:6430
#, python-format
msgid "Unexpected migration job type: %d"
msgstr ""

#: nova/virt/libvirt/driver.py:6497
#, python-format
msgid "Error monitoring migration: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:6693
#, python-format
msgid "plug_vifs() failed %(cnt)d. Retry up to %(max_retry)d."
msgstr ""

#: nova/virt/libvirt/driver.py:6977 nova/virt/libvirt/driver.py:7039
#, python-format
msgid ""
"Error from libvirt while getting description of %(instance_name)s: [Error"
" Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:7047
#, python-format
msgid ""
"Periodic task is updating the host stat, it is trying to get disk "
"%(i_name)s, but disk file was removed by concurrent operations such as "
"resize."
msgstr ""

#: nova/virt/libvirt/driver.py:7053
#, python-format
msgid ""
"Periodic task is updating the host stat, it is trying to get disk "
"%(i_name)s, but access is denied. It is most likely due to a VM that "
"exists on the compute node but is not managed by Nova."
msgstr ""

#: nova/virt/libvirt/driver.py:7062
#, python-format
msgid ""
"Periodic task is updating the host stats, it is trying to get disk info "
"for %(i_name)s, but the backing volume block device was removed by "
"concurrent operations such as resize. Error: %(error)s"
msgstr ""

#: nova/virt/libvirt/driver.py:7446
#, python-format
msgid "Failed to rollback snapshot (%s)"
msgstr ""

#: nova/virt/libvirt/driver.py:7726
#, python-format
msgid ""
"Ignoring supplied device name: %(device_name)s. Libvirt can't honour "
"user-supplied dev names"
msgstr ""

#: nova/virt/libvirt/driver.py:7747
#, python-format
msgid "Ignoring supplied device name: %(suggested_dev)s"
msgstr ""

#: nova/virt/libvirt/firewall.py:60
msgid ""
"Libvirt module could not be loaded. NWFilterFirewall will not work "
"correctly."
msgstr ""

#: nova/virt/libvirt/host.py:488
#, python-format
msgid "URI %(uri)s does not support events: %(error)s"
msgstr ""

#: nova/virt/libvirt/host.py:504
#, python-format
msgid "URI %(uri)s does not support connection events: %(error)s"
msgstr ""

#: nova/virt/libvirt/host.py:802
#, python-format
msgid "URI %(uri)s does not support full set of host capabilities: %(error)s"
msgstr ""

#: nova/virt/libvirt/host.py:944
#, python-format
msgid "couldn't obtain the memory from domain: %(uuid)s, exception: %(ex)s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:273
#, python-format
msgid "Unable to preallocate image at path: %(path)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:332
#, python-format
msgid ""
"Instance %(instance)s is using a backing file %(backing)s which does not "
"appear in the image service"
msgstr ""

#: nova/virt/libvirt/imagecache.py:553
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): warning -- an absent base file is in "
"use! instances: %(instance_list)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:591
#, python-format
msgid "%s swap image was used by instance but no back files existing!"
msgstr ""

#: nova/virt/libvirt/imagecache.py:617
#, python-format
msgid "Unknown base file: %s"
msgstr ""

#: nova/virt/libvirt/instancejobtracker.py:93
#, python-format
msgid ""
"Failed to kill a long running process %(pid)s related to the instance "
"when deleting it."
msgstr ""

#: nova/virt/libvirt/storage/lvm.py:78
#, python-format
msgid ""
"Volume group %(vg)s will not be able to hold sparse volume %(lv)s. "
"Virtual volume size is %(size)d bytes, but free space on volume group is "
"only %(free_space)db."
msgstr ""

#: nova/virt/libvirt/storage/lvm.py:226
#, python-format
msgid "ignoring missing logical volume %(path)s"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:290
#, python-format
msgid "image %(volume)s in pool %(pool)s can not be found, failed to remove"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:326
#, python-format
msgid "rbd remove %(volume)s in pool %(pool)s failed"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:402
#, python-format
msgid "snapshot(%(name)s) on rbd image(%(img)s) is protected, skipping"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:411
#, python-format
msgid "no snapshot(%(name)s) found on rbd image(%(img)s)"
msgstr ""

#: nova/virt/libvirt/volume/glusterfs.py:121
#: nova/virt/libvirt/volume/nfs.py:109 nova/virt/libvirt/volume/remotefs.py:64
#, python-format
msgid "%s is already mounted"
msgstr ""

#: nova/virt/libvirt/volume/iscsi.py:99
#, python-format
msgid "Ignoring VolumeDeviceNotFound: %s"
msgstr ""

#: nova/virt/libvirt/volume/volume.py:88
#, python-format
msgid "Unknown content in connection_info/qos_specs: %s"
msgstr ""

#: nova/virt/libvirt/volume/volume.py:115
#, python-format
msgid ""
"Unable to attach %(type)s volume %(serial)s with discard enabled: qemu "
"%(qemu)s and libvirt %(libvirt)s or later are required."
msgstr ""

#: nova/virt/vmwareapi/driver.py:199
#, python-format
msgid ""
"Running Nova with a VMware vCenter version less than %(version)s is "
"deprecated. The required minimum version of vCenter will be raised to "
"%(version)s in the 13.0.0 release."
msgstr ""

#: nova/virt/vmwareapi/driver.py:226
msgid "datastore_regex is ignored when PBM is enabled"
msgstr ""

#: nova/virt/vmwareapi/driver.py:425
#, python-format
msgid "The volume %s does not exist!"
msgstr ""

#: nova/virt/vmwareapi/driver.py:456
msgid ""
"Instance does not exists. Proceeding to delete instance properties on "
"datastore"
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:74
#, python-format
msgid "Unable to delete %(file)s. Exception: %(ex)s"
msgstr ""

#: nova/virt/vmwareapi/vif.py:113
#, python-format
msgid ""
"VMware vCenter version less than %(version)s does not support the 'ovs' "
"port type."
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1269
#, python-format
msgid "Failed to get cluster references %s"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1316
#, python-format
msgid ""
"vmware_ostype from image is not recognised: '%(ostype)s'. An invalid os "
"type may be one cause of this instance creation failure"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:392
#, python-format
msgid "Get esx cookies failed: %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:504
#, python-format
msgid ""
"Destination %s already exists! Concurrent moves can lead to unexpected "
"results."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1068
#, python-format
msgid ""
"In vmwareapi:vmops:_destroy_instance, got this exception while un-"
"registering the VM: %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1091
msgid ""
"In vmwareapi:vmops:_destroy_instance, exception while deleting the VM "
"contents from the disk"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1095
msgid "Instance does not exist on backend"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1857
#, python-format
msgid "Root disk file creation failed - %s"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:482
#, python-format
msgid "Virtual disk: %s of volume's backing not found."
msgstr ""

#: nova/virt/xenapi/agent.py:194
#, python-format
msgid "Ignoring error while configuring instance with agent: %s"
msgstr ""

#: nova/virt/xenapi/agent.py:270
#, python-format
msgid "Unable to update the agent due to: %(exc)s"
msgstr ""

#: nova/virt/xenapi/agent.py:422
msgid "Invalid 'agent_present' value. Falling back to the default."
msgstr ""

#: nova/virt/xenapi/driver.py:387
#, python-format
msgid "Could not determine key: %s"
msgstr ""

#: nova/virt/xenapi/host.py:293
#, python-format
msgid "Failed to extract instance support from %s"
msgstr ""

#: nova/virt/xenapi/vif.py:61
#, python-format
msgid "Failed to create vif, exception:%(exception)s, vif:%(vif)s"
msgstr ""

#: nova/virt/xenapi/vif.py:82
#, python-format
msgid "Fail to unplug vif:%(vif)s, exception:%(exception)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:328 nova/virt/xenapi/vm_utils.py:343
msgid "VM already halted, skipping shutdown..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:846
#, python-format
msgid "Multiple base images for image: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:985
#, python-format
msgid "Attempted auto_configure_disk failed because: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1236
#, python-format
msgid ""
"Fast cloning is only supported on default local SR of type ext. SR on "
"this system was found to be of type %s. Ignoring the cow flag."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1311
#, python-format
msgid "Unrecognized cache_images value '%s', defaulting to True"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1387
#, python-format
msgid "Invalid value '%s' for torrent_images"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1410
#, python-format
msgid "Invalid value '%d' for image_compression_level"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1842
#, python-format
msgid "Retry SR scan due to error: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1875
#, python-format
msgid "Flag sr_matching_filter '%s' does not respect formatting convention"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2587
msgid "ipxe_boot_menu_url not set, user will have to enter URL manually..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2593
msgid "ipxe_network_name not set, user will have to enter IP manually..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2604
#, python-format
msgid ""
"Unable to find network matching '%(network_name)s', user will have to "
"enter IP manually..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2628
#, python-format
msgid "ISO creation tool '%s' does not exist."
msgstr ""

#: nova/virt/xenapi/vmops.py:456
msgid "ipxe_boot is True but no ISO image found"
msgstr ""

#: nova/virt/xenapi/vmops.py:620
msgid "Timeout waiting for vif plugging callback"
msgstr ""

#: nova/virt/xenapi/vmops.py:633
#, python-format
msgid "Neutron Reported failure on event %(event)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1205
#, python-format
msgid "_migrate_disk_resizing_up failed to rollback: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1339
msgid ""
"Reboot failed due to bad volumes, detaching bad volumes and starting "
"halted instance"
msgstr ""

#: nova/virt/xenapi/vmops.py:1417
msgid "Unable to update metadata, VM not found."
msgstr ""

#: nova/virt/xenapi/vmops.py:1569
msgid "VM is not present, skipping destroy..."
msgstr ""

#: nova/virt/xenapi/vmops.py:1706
msgid "VM is not present, skipping soft delete..."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:251
msgid "Cannot purge SR with referenced VDIs"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:268
#, python-format
msgid "Ignoring exception %(exc)s when getting PBDs for %(sr_ref)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:276
#, python-format
msgid "Ignoring exception %(exc)s when unplugging PBD %(pbd)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:300
#, python-format
msgid "Mountpoint cannot be translated: %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:149
#, python-format
msgid "Skipping detach because VBD for %s was not found"
msgstr ""

#: nova/virt/xenapi/client/session.py:247
#, python-format
msgid "%(plugin)s.%(fn)s failed. Retrying call."
msgstr ""

#: nova/virt/xenapi/client/session.py:256
#, python-format
msgid ""
"Lost connection to XenAPI during call to %(plugin)s.%(fn)s.  Retrying "
"call."
msgstr ""

#: nova/virt/xenapi/image/bittorrent.py:73
msgid ""
"Value specified in conf file for xenserver.torrent_base_url does not "
"contain a slash character, therefore it will not be used as part of the "
"torrent URL. Specify a valid base URL as defined by RFC 1808 (see step "
"6)."
msgstr ""

#: nova/volume/cinder.py:135
msgid ""
"Cinder V1 API is deprecated as of the Juno release, and Nova is still "
"configured to use it. Enable the V2 API in Cinder and set "
"cinder.catalog_info in nova.conf to use it."
msgstr ""

#: nova/volume/cinder.py:389
#, python-format
msgid ""
"attachment_id couldn't be retrieved for volume %(volume_id)s with "
"instance_uuid %(instance_id)s. The volume has the 'multiattach' flag "
"enabled, without the attachment_id Cinder most probably cannot perform "
"the detach."
msgstr ""

#: nova/volume/cinder.py:399
#, python-format
msgid ""
"attachment_id couldn't be retrieved for volume %(volume_id)s. The volume "
"has the 'multiattach' flag enabled, without the attachment_id Cinder most"
" probably cannot perform the detach."
msgstr ""

#: nova/volume/encryptors/__init__.py:70
#, python-format
msgid "Volume %s should be encrypted but there is no encryption metadata."
msgstr ""

#: nova/volume/encryptors/luks.py:42
#, python-format
msgid "isLuks exited abnormally (status %(exit_code)s): %(stderr)s"
msgstr ""

